name: Deploy Staging Site

on:
  push:
    # build staging whenever someone pushes to main
    branches: [main]

env:
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID_STAGING }}
  BASE_PATH: "/year/2026" # we are ONLY deploying to this base path, do not add a trailing slash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_STAGING }}

      - name: Sync S3 bucket
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_STAGING }}${{ env.BASE_PATH }}/ --delete

      - name: Invalidate CloudFront
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "${{ env.BASE_PATH }}*"

# note there is no trailing slash between env.BASE_PATH and the *
